name: Go run Tests

on: [push]

jobs:
  Go Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.13

      - name: Test
        run: go test -v ./...